### PR TITLE
Working files (only no password)

### PR DESCRIPTION
**Pull request by hellgatex31**
Hi guys, I've added all the files that are working for me. Do make the changes to your SQL for it to work because email is not a PK

### CODE REVIEW

**Comment by peininging** [comment]
Works on my side, thanks!

**Comment by EdwardBrick** [comment]
Alright it works, want me to merge?

**Comment by hellgatex31** [comment]
It's okay, I will merge :)

**Comment by EdwardBrick** [comment]
Thanks

**Pull request merged**
